// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__gtDFvjZV379qZ6RVxY6Y_xZvdPqtas',
    appId: '1:1082191155637:web:1aa923ca5ab8df3df5c9fc',
    messagingSenderId: '1082191155637',
    projectId: 'phoneauthflutter-865e3',
    authDomain: 'phoneauthflutter-865e3.firebaseapp.com',
    storageBucket: 'phoneauthflutter-865e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnLCnvxGbetv2ijqBd2UAu4zDw654Hxk',
    appId: '1:1082191155637:android:019aaa5c4aa6f2f7f5c9fc',
    messagingSenderId: '1082191155637',
    projectId: 'phoneauthflutter-865e3',
    storageBucket: 'phoneauthflutter-865e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczRn6uVfU2DkXVCR0t4fBXi7eSfJlofo',
    appId: '1:1082191155637:ios:9b73af69a3188056f5c9fc',
    messagingSenderId: '1082191155637',
    projectId: 'phoneauthflutter-865e3',
    storageBucket: 'phoneauthflutter-865e3.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczRn6uVfU2DkXVCR0t4fBXi7eSfJlofo',
    appId: '1:1082191155637:ios:4eb4881647afee3ef5c9fc',
    messagingSenderId: '1082191155637',
    projectId: 'phoneauthflutter-865e3',
    storageBucket: 'phoneauthflutter-865e3.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebase.RunnerTests',
  );
}
